"""add async incident processing state

Revision ID: a473b642b962
Revises: fdbeee0db525
Create Date: 2026-09-27 21:04:58.090025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a473b642b962'
down_revision: Union[str, Sequence[str], None] = 'fdbeee0db525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('status', sa.String(length=20), server_default='queued', nullable=False))
    op.add_column('incidents', sa.Column('job_id', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('incidents', 'result',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_incidents_job_id'), 'incidents', ['job_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_job_id'), table_name='incidents')
    op.alter_column('incidents', 'result',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('incidents', 'updated_at')
    op.drop_column('incidents', 'error_message')
    op.drop_column('incidents', 'job_id')
    op.drop_column('incidents', 'status')
    # ### end Alembic commands ###
